### ISSUE TITLE
STORY 1: notify when the booking has been accepted

### ISSUE THREAD

**Issue by paologastaldi-polito** [se2-group2/PULSeBS#7]
I would like to see a notification (a small popup or a message) when I book a lecture before it disappears and moves to the booked lectures list, so I'm sure my booking request has been accepted.
Otherwise, booked and not-booked lectures can be shown in the same list with different colours (or other graphical ways).

Juliana, master student

**Comment by GaetanoPrudente** [comment]
Solved
